### ISSUE TITLE
There's no way to generate the needed .hdf2 files.

### ISSUE THREAD

**Issue by Iamgoofball** [amidos2006/DeepTingle#3]
Unless I'm missing something, you can't generate them.

**Comment by amidos2006** [comment]
You can generate them, Just open this file "DeepTingle Words.ipynb"
And run the first three code blocks.
Make sure that all the paths are correct. In the 3rd code block there is a line for loading weights (remove that line) and change the output path to an existing folder on your machine.

The reason there is too much modifications is Gihub didn't allow to upload files bigger than 100mb so I didn't upload the hdf5.

If you want to use the files directly instead of training, you can download it http://www.deeptingle.net/deeptingleweights/WordBased.hdf5

Tell me if you have any problems (I will update the repo to take care of that problem).

Thanks for pointing that out

**Comment by Iamgoofball** [comment]
Oh. That makes so much sense. Thanks!

**Comment by Iamgoofball** [comment]
Out of curiosity, what Keras backend did you use?

**Comment by amidos2006** [comment]
Tensorflow :) any other question?
